### ISSUE TITLE
Incompatible with Lithium (1.17.1)

### ISSUE THREAD

**Issue by KyGost** [waterlilly-lilly/editableplayernbthack#1]
It seems this mod is unfortunately incompatible with Lithium 1.17 due to hopperOptimisations merging in this version:
```
[STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[STDERR]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[STDERR]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[STDERR]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[STDERR]: at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[STDERR]: at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[STDERR]: ... 9 more
[STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[STDERR]: at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
[STDERR]: at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[STDERR]: at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[STDERR]: at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
[STDERR]: at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
[STDERR]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[STDERR]: at net.minecraft.class_3164.<clinit>(class_3164.java:53)
[STDERR]: at net.minecraft.class_3050.method_13298(class_3050.java:491)
[STDERR]: at net.minecraft.class_3050.method_13271(class_3050.java:133)
[STDERR]: at net.minecraft.class_2170.<init>(class_2170.java:150)
[STDERR]: at net.minecraft.class_5350.<init>(class_5350.java:39)
[STDERR]: at net.minecraft.class_5350.method_29466(class_5350.java:88)
[STDERR]: at net.minecraft.server.Main.main(MixinMain.java:147)
[STDERR]: ... 14 more
[STDERR]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [lithium.mixins.json:block.hopper.EntityDataObjectMixin]: from phase [DEFAULT] in config [lithium.mixins.json] FAILED during APPLY
[STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
[STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
[STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
[STDERR]: ... 27 more
[STDERR]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")]: on net/minecraft/class_3169::updateEntityTrackerEngine with priority 1000 cannot inject into net/minecraft/class_3169::method_13880(Lnet/minecraft/class_2487;)V merged by dev.waterlilly.editableplayernbthack.mixin.AllowPlayerDataEditMixin with priority 1000 [PREINJECT Applicator Phase -> lithium.mixins.json:block.hopper.EntityDataObjectMixin -> Prepare Injections -> -> handler$zcd000$updateEntityTrackerEngine(Lnet/minecraft/class_2487;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
[STDERR]: at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
[STDERR]: at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
[STDERR]: at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
[STDERR]: at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
[STDERR]: at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
[STDERR]: at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
[STDERR]: at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[STDERR]: at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[STDERR]: ... 27 more
```

**Comment by DBTDerpbox** [comment]
should bring up, the source for this project was moved and this issue was fixed in 1.1.0

fixed version: https://modrinth.com/mod/editableplayernbthack/version/1.1.0
new source location: https://git.soulforged.studio/mae/editable-player-nbt-hack
