### ISSUE TITLE
Possible 1.19 compatibility?

### ISSUE THREAD

**Issue by dAKirby309** [waterlilly-lilly/editableplayernbthack#2]
Is it possible to somehow make this compatible with Fabric 1.19.0? I'm very saddened that it isn't working on that version, but it does on 1.19.2 as I'm really wanting something like this for a very particular project on a 1.19.0 modded server I'm setting up...

[latest.log](https://github.com/waterlilly-lilly/editableplayernbthack/files/13168859/latest.log)
```[12:15:59] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.14
[12:16:00] [ForkJoinPool-1-worker-3/WARN]: Mod nyfsquiver uses the version Fabric-0.5.0-1.19-rc2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[12:16:00] [main/WARN]: Mod resolution failed
[12:16:00] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED editableplayernbthack 1.1.0-1.19.2 {depends minecraft @ [1.19.2]}, ROOT_FORCELOAD_SINGLE editableplayernbthack 1.1.0-1.19.2]
[12:16:00] [main/INFO]: Reason: [HARD_DEP editableplayernbthack 1.1.0-1.19.2 {depends minecraft @ [1.19.2]}]
[12:16:00] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-keybindings-v0, fabric-textures-v0, modmenu, malilib, fabric-screen-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1, coat, fabric-renderer-registries-v1, tweed4_tailor_screen, fabric-models-v0, tweed4_tailor_coat, fabric-rendering-v0, fabric-rendering-v1, fabric-key-binding-api-v1]
[12:16:00] [main/INFO]: Fix: add [], remove [], replace [[editableplayernbthack 1.1.0-1.19.2] -> add:editableplayernbthack 1 ([(-?,?)])]
[12:16:00] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Editable Player NBT Hack' (editableplayernbthack) 1.1.0-1.19.2 with any version that is compatible with:
		 - minecraft 1.19
Unmet dependency listing:
	 - Mod 'Editable Player NBT Hack' (editableplayernbthack) 1.1.0-1.19.2 requires version 1.19.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.14.jar:?]
```

**Comment by dAKirby309** [comment]
Ok I managed to solve this by changing one line of code in the fabric.mod.json file from 1.19.2 to 1.19

Thank you for this! Hopefully it can do all I want it to do. :)

**Comment by dAKirby309** [comment]
Ok I managed to solve this by changing one line of code in the fabric.mod.json file from 1.19.2 to 1.19

Thank you for this! Hopefully it can do all I want it to do. :)
